/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Logica.Conexion;
import Logica.HabitacionData;
import Logica.ReservaData;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dani
 */
public class PrimerVista extends javax.swing.JFrame {
    private Conexion con;

    public PrimerVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        verificarFechasReservas();
        mostrarTodas();
    }

    
    //El siguiente metodo invoca al metodo verificarFechaSalida de la clase ReservaData en el cual se verifica
    //que si la fecha de salida es menor a la actual, entonces la reserva pasa de estado 1 a 0, es decir de activa a inactiva.
    public void verificarFechasReservas(){
        try {
            con = new Conexion("jdbc:mysql://localhost/elgranhotel", "root", "");
            ReservaData thd = new ReservaData(con);
            thd.verificarFechaSalida();

        } catch (Exception e) {
            System.out.println("error reservacliente.java");
        }
    }

    public void mostrarTodas() {
        try {
            con = new Conexion("jdbc:mysql://localhost/elgranhotel", "root", "");
            ReservaData todas = new ReservaData(con);

            DefaultTableModel modelo;
            modelo = todas.mostrartodas();
            
            String idhab;
            String estado;
            int id_habit;
 
            //Aqui habilitare las habitaciones de las reservas que ya han caducado.
            for (int i = 0; i < modelo.getRowCount(); i++) {
                idhab = (String) modelo.getValueAt(i, 2);   //Obtengo el id de la habitacion
                estado = (String) modelo.getValueAt(i, 7);  //Obtengo el estado de la reserva
                //System.out.println(idhab);
                //Aqui verifico lo siguiente: si el estado de la reserva es 0, entonces obtengo el ID de la habitacion,
                //la busco y le cambio el estado de ocupada a libre (e caso de que este ocupada):
                if (estado.equals("0")){
                    id_habit = Integer.parseInt(idhab);                    
                    desocuparHabitacion(id_habit);
                }
            }

        } catch (Exception e) {
            System.out.println("error en mostrarTodas");
        }
    }

    public void desocuparHabitacion(int id){
        try {
            con = new Conexion("jdbc:mysql://localhost/elgranhotel", "root", "");
            HabitacionData porhab = new HabitacionData(con);

            porhab.desocupar(id);
        } catch (Exception e) {
            System.out.println("error desocuparHabitacion");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsalir = new javax.swing.JButton();
        btnreserva = new javax.swing.JButton();
        btnsistema = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/salirsistema_opt.jpg"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 67));

        btnreserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/hagareserva_opt.jpg"))); // NOI18N
        btnreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnreserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 200, 67));

        btnsistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/ingresar_opt.jpg"))); // NOI18N
        btnsistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 200, 67));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/2_opt (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservaActionPerformed
        //Aqui debo abrir la pagina de INICIO con el formulario de reserva:
        this.dispose();
        Inicio n = new Inicio(0);
        n.setVisible(true);   
        
    }//GEN-LAST:event_btnreservaActionPerformed

    private void btnsistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsistemaActionPerformed
        //Aqui debo ingresar al sistema:
        this.dispose();
        Inicio n = new Inicio();
        n.setVisible(true);
    }//GEN-LAST:event_btnsistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimerVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreserva;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsistema;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
